search_queries = [
    "problem with...",
    "problems with...",
    "issue with...",
    "issues with...",
    "issue of...",
    "trouble with...",
    "struggling with...",
    "help needed...",
    "need help...",
    "help for...",
    "help with...",
    "having problems...",
]

remove_phrases = [
    "having problems",
    "problem",
    "problems",
    "issue",
    "issues",
    "trouble",
    "struggling",
    "help needed",
    "need help",
    "help for",
    "help ",
]

random_searches = [
    "Best budget smartphones",
    "Tips for improving productivity",
    "Healthy meal prep ideas",
    "DIY home decor projects",
    "Book recommendations for sci-fi lovers",
    "Beginner-friendly yoga routines",
    "Travel destinations off the beaten path",
    "Advice for first-time pet owners",
    "Career advice for recent graduates",
    "Coding bootcamp reviews",
    "Meditation techniques for stress relief",
    "Personal finance tips for saving money",
    "Home workout routines without equipment",
    "Vegan recipes for beginners",
    "Relationship advice for long-distance couples",
    "Investing strategies for beginners",
    "Gaming communities for indie games",
    "Tips for starting a small business",
    "Mental health support groups",
    "Sustainable living tips",
    "Fashion inspiration for minimalist wardrobes",
    "Parenting advice for toddlers",
    "Technology news and updates",
    "Home gardening tips for beginners",
    "Language learning resources for beginners",
    "Financial independence and retire early (FIRE) discussions",
    "Home renovation ideas on a budget",
    "Fitness challenges for motivation",
    "Podcast recommendations for personal development",
    "Cooking tips and tricks from professional chefs",
    "Conspiracy theories and discussions",
    "Cybersecurity tips for staying safe online"
]
